### ISSUE TITLE
Investigate reading the HX711

### ISSUE THREAD

**Issue by amotl** [hiveeyes/terkin-datalogger#81]
While [discussing](https://github.com/hiveeyes/terkin-datalogger/pull/80/files/f4e3e7d3f9125ad82c933fa8750b4ca784315f8a#diff-aacfe5da8fa50c9535f83449f906ded9) #80, @poesel and I stumbled over the code at [hx711.py#L121-L128](https://github.com/hiveeyes/terkin-datalogger/blob/0.10.0/src/lib/terkin/lib/hx711.py#L121-L128). We took the original implementation from [hx711.py#L41-L46](https://github.com/geda/hx711-lopy/blob/9cc6de8d878abfe3be6a3fb43e4b341f816a4952/hx711.py#L41-L46) by @geda.

When comparing it to the canonical HX711 library for Arduino by @bogde at [HX711.cpp#L110-L167](https://github.com/bogde/HX711/blob/0.7.4/src/HX711.cpp#L110-L167), I come to the conclusion we should protect the **whole** read sequence from system interrupts, right?

 cc @robert-hh

**Comment by poesel** [comment]
> we should protect the **whole** read sequence from system interrupts, right?

That would be nice but disabling the IRQs for such a long time causes a crash. I know, I tried. :(

**Comment by robert-hh** [comment]
I just pulled up the test files from my HX711 test. Using >2 Million test, I did not see an indication of a false read either at the SPI or Bit-Bang solution. Comparing shorter test series of 100000 samples each with different setting (e.g. 10 samples/sec and 80 samples/sec) also revealed no substantial difference between SPI and bit-banging. The set-up was for all test a weight sensor attached to a table and a 10 kg piece of steel hanging on it. The difference seen may be caused by a temperature drift. At 10 samples/sec, it takes 3 hrs for a test sequence.
@andreas: The original @geda implementation did not disable interrupts.  So it had sometimes long pulses, resulting in read errors. So I made a PR to change that.
